module.exports = {
    onboardingActivities: {
        indoor: [
            {
                name: 'The Manhattan Well Murder',
                indoor_outdoor: 0,
                location: '129 Spring StNew York, New York, 10012United States',
                description: 'A sealed well underneath former Manhattan Bistro in Soho was the site of the 1799 murder of Gulielma Elmore Sands, who was strangled and dumped in the well on Spring St.The accused murderer was Levi Weeks, a fellow boarder in a house on Greenwich Street, whom Sands had been secretly seeing. Weeks was masterfully defended in court by Alexander Hamilton and Aaron Burr. As a result, the jury delivered an acquittal after just five minutes of deliberation.Weeks, nevertheless, had to leave the city, as he was widely condsidered guilty.The well is not open to the public, but it is sometimes accessible upon special request provided its status as one of the Travel Channel’s “10 Most Haunted Places in America.”The Manhattan Bistro above the site is also now closed, but it is visible in the lower level of a clothing store called COS.Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzZiMWJlOGI5ZDRhMzM1YTQ5ZGRhZGQzNTdiNTFmNjJiTlktQkc2ODZfU1BBQ0VzX0dfMjAxMTEwMjQxODE3NDEuanBlZyJdLFsicCIsInRodW1iIiwiNjAweDQwMCswKzAiXSxbInAiLCJjb252ZXJ0IiwiLXF1YWxpdHkgODEgLWF1dG8tb3JpZW50Il0sWyJwIiwidGh1bWIiLCIzNzJ4MjQ4IyJdXQ/NY-BG686_SPACEs_G_20111024181741.jpeg',
                website: 'https://www.atlasobscura.com/places/The-Manhattan-Well-Murder',
                categories: {'food and drink': 1, 'society': 1, 'home and garden': 1}
            },
            {
                name: 'Titanic Memorial',
                indoor_outdoor: 0,
                location: 'Titanic Memorial ParkNew York, New York, 10038United States',
                description: 'The Titanic Memorial lighthouse has stood at the entrance to the South Street Seaport since 1976. Before it moved to its current home, the memorial was erected on top of the Seamen’s Church Institute in 1913 after the Unsinkable Molly Brown insisted that a monument to those lost in the Titanic be erected.Margaret Brown, better known as Molly, was as stubborn after coming back to dry land as she was during her alleged rescue of fellow passengers during the Titanic’s sinking. Always larger than life, Brown insisted that a 60-foot-high lighthouse be erected in Lower Manhattan. When it was first built, just a year after the Titanic sank, a time ball was installed above the lighthouse, and dropped at noon every day in remembrance of those who perished.After the ball ceased to keep time in 1967, the lighthouse was moved off the roof of the Seamen’s Church Institute and became a part of the South Street Seaport Museum at the corner of Fulton and Pearl. As conspicuous as Molly Brown would have wanted it, the monument greets visitors to the Seaport with a reminder of the tragedy of April 15, 1912.Four blocks east of Fulton Street Subway Station. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzk0NGQ2YThmN2UwZGY5MTgwMjdmYzI3OWYxYmI5NjExOWVjYjA4YmUuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiMzcyeDI0OCMiXV0/944d6a8f7e0df918027fc279f1bb96119ecb08be.jpg',
                website: 'https://www.atlasobscura.com/places/Titanic-Memorial',
                categories: {'law, govt and politics': 1, 'hobbies and interests': 1, 'society': 1}
            },
            {
                name: 'Trinity Churchyard',
                indoor_outdoor: 0,
                location: '75 BroadwayNew York, New York, 10006United States',
                description: 'Now dwarfed by the surrounding Wall Street skyscrapers, Trinity Church was the tallest building in New York City when it was completed in 1846. The surrounding stones are even older than the church, many dating back to the 17th century. The Trinity Churchyard in Lower Manhattan is part of the Episcopal Parish of Trinity Church, which has three burial grounds in the city including nearby St. Paul’s and Trinity Cemetery in Washington Heights. While the most notable interment of Trinity Churchyard is definitely Alexander Hamilton, the whole burial ground has a wealth of 17th- and 18th-century funerary symbolism, with plenty of flying skulls and hourglasses. For example, there’s the two-sided tombstone of Richard Churcher, a five-year-old boy who died in 1681. His tombstone is the oldest carved gravestone in the city, and on the back has a dimensional hourglass and skull and bones. James Leeson also has a very unusual stone. The 18th-century gentleman requested that along with classical Masonic markings and funeral iconography his tombstone be marked with an insoluble message. The bizarre-looking words are written in a “pigpen” cypher, sometimes used by Masons to code their text and keep their knowledge out of the hands of the curious. The symbols actually mean “Remember Death,” a classic message for the 18th century which becomes, through the form of an enigma, a version of the well-known “Memento Mori.” The grave is on the Broadway side of the cemetery, facing the fence.Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL2MwNTM1ZTJmYTI0YmM2ZTU2MF90cmluaXR5Y2h1cmNoeWFyZDA2LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA4MSAtYXV0by1vcmllbnQiXSxbInAiLCJ0aHVtYiIsIjM3MngyNDgjIl1d',
                website: 'https://www.atlasobscura.com/places/Trinity-Churchyard',
                categories: {'art and entertainment': 1, 'society': 1, 'science': 1}
            },
            {
                name: 'Mysterious Bookshop',
                indoor_outdoor: 0,
                location: '58 Warren StNew York, New YorkUnited States',
                description: 'Mysteries have always been around and always been popular, but they haven’t always been respected. Otto Penzler has had a significant hand in that transformation. He’s probably the most important figure in the history of mystery fiction who’s never written a mystery story. You get into Otto Penzler’s New York office through a door in the Mysterious Bookshop, the world’s oldest and biggest bookstore focusing on mystery, crime fiction, espionage, and thrillers. The door is roped off with a big X made of yellow police tape reading CRIME SCENE DO NOT CROSS. Down a flight of stairs, his office is a low-ceilinged basement cube with floor-to-ceiling bookshelves on all four sides, stocked with anthologies and first editions as well as a random sampling of mass-market hardcovers and paperbacks. If the office was a store by itself, it would be the second-best mystery bookstore in the world. Penzler is the owner of the Mysterious Bookshop (founded 1979) as well as The Mysterious Press, a publishing imprint he founded in 1975, and mysteriouspress.com, his ebook publisher. He has published most of the greats of mystery and crime fiction: Raymond Chandler, James M. Cain, James Ellroy, Ross Thomas, Patricia Highsmith, Ross Macdonald, Ed McBain. Any of the major authors he hasn’t published are probably at least good friends of his.The Mysterious Bookshop itself. Today the store is down in Tribeca, on a block that doesn’t suggest anything important in the literary world. It’s next to a Le Pain Quotidien and a few doors down from a 7-Eleven. (It was first located on 56th Street in Manhattan, in a building Penzler owned because it was cheaper to buy—New York was different back then.) Inside, every square inch of walls leading up to what must be 20-foot ceilings are packed with any book in which someone violently dies. There is an entire section for Sherlock Holmes books, including the many spinoffs written by dozens of authors. There are copies of long-defunct detective magazines like Black Mask. There is an entire section for what Penzler calls bibliomysteries—mystery books involving mysterious books. Murdered librarians, valuable manuscripts, that kind of thing.The bookstore is not twee. There are no props, aside from the caution tape; no pranks, no cute designs or artworks. This is a temple to the noble mystery, a place where people who can name all of Donald E. Westlake’s pseudonyms talk about one of the most enduring genres in the history of literature.Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL2U4ZThhYWM4OWNiZDI5MjhjOV9pbWFnZSAoNjYpLmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA4MSAtYXV0by1vcmllbnQiXSxbInAiLCJ0aHVtYiIsIjM3MngyNDgjIl1d/image%20%2866%29.jpg',
                website: 'https://www.atlasobscura.com/places/Mysterious-Bookshop',
                categories: {'arts and entertainment': 1, 'art and entertainment': 1, 'society': 1}
            },
            {
                name: 'New York Federal Gold Vault',
                indoor_outdoor: 0,
                location: '44 Maiden Ln.New York, New York, 10038United States',
                description: 'The largest accumulation of gold in human history is located deep underneath the heart of Manhattan’s financial district, at the New York Federal Reserve Bank. Some 80 feet beneath sidewalk level, the Fed’s special vault is built in bedrock and entrusted with deposits from central banks across the globe. Inside sits 7,000 tons of glittering gold bars—around 5 percent of all of the gold ever mined.The only way into the vault is via a cylindrical entryway that rotates at the turn of a wheel. A sliver-shaped pie chunk of the cylinder has an opening, that when properly aligned with the entry hallway allows access to the treasure inside. Inside there are 122 separate mini vaults (one for each different country), plus a “library vault” for account holders with smaller deposits. The Fed considers each gold bar as a non-fungible individual because of variations in purity and weight. As a result they carefully track each of the deposits, so if you give them a particular bar you can later retrieve that exact one. The Fed’s gold vault really doesn’t cater to millionaires and billionaires, though; the customers are sovereign nations. While the list of account holders is a closely guarded secret, think of the likes of Bank of England, Banque de France, and Deutsche Bundesbank. Foreign countries store their gold in New York for the benefits of convenience and centrality. One of the perks of centralizing everything in one spot is that countries can transfer gold amongst themselves by simply moving bars from one compartment to another, at a modest handling cost of $2 per bar.Perhaps the most amazing thing about the New York Fed gold vault is that it offers public tours (although the website says that new bookings are currently unavailable). That’s a remarkable feat considering the security at similar facilities like the Gold Bullion Depository at Fort Knox, which bars the likes of reporters, members of congress and former presidents.Fulton street Station on the 2,3 or 4,5 Trains. The tour is free.Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzZiMWJlOGI5ZDRhMzM1YTQ5ZGRhZGQzNTdiNTFmNjJiZ29sZDAxLmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA4MSAtYXV0by1vcmllbnQiXSxbInAiLCJ0aHVtYiIsIjM3MngyNDgjIl1d/gold01.jpg',
                website: 'https://www.newyorkfed.org/aboutthefed/visiting.html',
                categories: {'finance': 1, 'travel': 1, 'business and industrial': 1}
            },
            {
                name: 'Explorers Club Headquarters',
                indoor_outdoor: 0,
                location: '46 E. 70th StreetNew York, New York, 10021United States',
                description: 'Behind impressive heavy doors and ornate turn-of-the-century stained glass windows lies the Explorers Club headquarters on East 70th Street.Founded in 1904 by seven leading polar explorers of the era, the Explorers Club fosters the scientific exploration of land, sea, air and space. The 1910 Jacobean revival mansion was originally built for Stephen Clark, grandson of the co-founder of the Singer Sewing Machine Company. The Explorers Club purchased the building from the Clark family in 1960 after Stephen’s death. It became the international headquarters in 1965. Prior to this, they had several locations in New York City.It is known as the Lowell Thomas building, named after the famed writer, broadcaster and Explorers Club member best known for making Lawrence of Arabia famous.A century’s worth of exploration treasures fill the floors. The ground floor member lounge houses a few of their polar artifacts. On your way up to the second floor, you won’t be able to miss the giant globe used by Thor Heyerdahl to plan his famous Kon-Tiki expedition.Percy, the polar bear, greets you on the second floor. As you head into the library, you will see The Rescue of Greeley, painted within hours of their rescue in 1884. The library holds a tiny fraction of the 13,000 books that make up the research and archives collection. All lectures and events are held in the Clark room. The walls proudly display a few of the retired expedition flags from historic explorations. A sled from the 1909 North Pole expedition and an extremely rare set of double elephant tusks from the Congo can also be found here.The uppermost floor is home to the research archives, holding the club’s impressive collection of 13,000 books, 1,000 museum objects, 5,000 maps and 500 films.The Gallery on the top floor is the room everyone wants to see. In the early days of the Explorers Club when travel was difficult and field photography was relatively new, hunting and taxidermy were thought to be the best way to preserve animals for education and research. Here you will see taxidermied animals from many decades past. Objects from the far corners of the world, including a narwhal tusk, wooly mammoth tusk (ask about the famous 1951 Explorers Club dinner) and the famous yeti scalp.Scaffolding was recently removed, revealing the results of a five-year long refurbishment of the building’s facade, but work continues to preserve the building. Visitors are welcome during opening hours. Group tours can be scheduled by contacting reservations. Regular talks with exploration greats are held in the Clark Room from September - June. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzkwMjZlNDgyYWVkMjI3YjQ5M2EzMjc4OGI4MDA4Yzc3NjFmMzgxYWIuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiMzcyeDI0OCMiXV0/9026e482aed227b493a32788b8008c7761f381ab.jpg',
                website: 'http://www.explorers.org/index.php/about/history/a_gathering_place',
                categories: {'shopping': 1, 'travel': 1, 'business and industrial': 1}
            }
        ],
        outdoor: [
            {
                name: 'The SeaGlass Carousel',
                indoor_outdoor: 1,
                location: 'State Street & Water Street(between the Battery Park Underpass and State St)New York, New York, 10004United States',
                description: 'The SeaGlass Carousel in New York City’s Battery Park is housed inside a glass-paneled nautilus shell that sits atop the site of the original New York Aquarium.Opened in August 2015, the carousel is the creation of the Battery Conservancy and George Tsypin, a renowned opera and theater designer who is the man behind the staging of LaScala operas, the Sochi Olympics, and the Spider-man Broadway musical. Constructed as a public-private project, it took 10 years and several million dollars to bring the SeaGlass Carousel to life.The SeaGlass Carousel features 30 fiberglass fish spotlighting 12 different species, while the mechanics are unique in that there’s no traditional center pole. By putting individual motors for each fish below the floor, the riders have unobstructed views while the fish both spin independently and swirl around each other as though swimming through the ocean.Rides of the SeaGlass Carousel will also experience a changing LED light display that makes one feel as though they are truly underwater. To add to the overall experience, each fiberglass fish contains its own speakers that play aquatic sounds and music specifically composed for the ride. Each of the fish in the carousel is modeled after an actual species ranging from tall angelfish to the much smaller clown triggerfish. No matter which you choose, it will resemble one underwater lifeform or another that can actually be found out in the oceanThe SeaGlass Carousel is located in Manhattan\'s Battery Park and is easily accessible by several New York City subway lines, including the 1, R, and W. The carousel can also be reached via the M5, M15, M15 SelectBusService, and M20 bus to South Ferry.The SeaGlass Carousel is open seven days a week from 10 am to 10 pm. Tickets cost $5 USD, while children 12 months and younger ride for free. Before visiting the SeaGlass Carousel, it is advised to check the carousel\'s Facebook page for any unexpected closures due to weather. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzhhNTJlMTRiNzY2YzlkMjE1ZF9SaWRlIDQuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiMzcyeDI0OCMiXV0',
                website: 'https://www.nycgovparks.org/parks/septuagesimo-uno/',
                categories: {'pets': 1, 'travel': 1, 'family and parenting': 1}
            },
            {
                name: 'Slocum Memorial Fountain',
                indoor_outdoor: 1,
                location: 'Tompkins SquareNew York, New York, 10009United States',
                description: 'Prior to September 11, the General Slocum steamship fire was the greatest loss of life in any disaster in New York City history. However, its memorial in Tompkins Square is easily overlooked.The nine-foot stele sculpted by Bruno Louis Zimm from pink Tennessee marble shows two children in relief with the words “They were Earth’s purest children, young and fair.” A lion’s head spits out water into a small basin. On June 15, 1904, some 300 of the 1,300 passengers to board the General Slocum excursion steamer were children under the age of 10.Almost all of the passengers were from Kleindeutschland, or Little Germany, an area in today’s East Village. The Slocum had been chartered by the St. Mark’s Evangelical Lutheran Church on Sixth Street and Second Avenue for their annual picnic. As it was a weekday, most of the passengers were women and children. Just 20 minutes after the boat left the Third Street pier, a fire broke out.Pandemonium ensued. The life vests turned out to be worse than useless, sinking with whomever jumped in (most of the passengers were unable to swim), and lifeboats were painted to the side of the ship. The captain sped the boat towards North Brother Island in an attempt to beach it, but the speed just fanned the flames. By the time the boat arrived to the quarantine hospital island, it was consumed in fire. Patients and doctors attempted to save people by tossing them debris. By the end of the day, around 1,000 people were dead.Many of the deceased were interred in Middle Village’s Lutheran cemetery, where a monument was built in 1905. The Tompkins Square fountain was dedicated in 1906. As for Little Germany, with mostly men left behind with their families dead, they dissipated throughout the city, and you can only find small traces of this past in the rare German sign on an old building in the East Village. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL2Y3YzIyMGUyZGU2NmYxMzJhNF8xNDU4MTYwNjk2N181M2I5NmNkMWZhX2guanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiMzcyeDI0OCMiXV0',
                website: 'http://www.nycgovparks.org/parks/tompkinssquarepark/highlights/17099',
                categories: {'family and parenting': 1, 'automotive and vehicles': 1, 'law, govt and politics': 1}
            },
            {
                name: 'Vanderbilt Tennis Club',
                indoor_outdoor: 1,
                location: '15 Vanderbilt Ave4th FloorNew York, New York, 10017United States',
                description: 'Little known to most commuters there have been posh, exclusive tennis courts hidden on the upper levels of Grand Central Terminal since the 1960’s, but the Vanderbilt Tennis Club is the current purveyor of courts behind the famous vaulted windows. A fitness center has existed in Grand Central Terminal since the 1960’s, originally in the form of the Vanderbilt Athletic Club, which featured two clay tennis courts (and oddly, a 65-foot indoor ski slope). However by the 80’s this club had fallen into disrepair. In 1984, thanks to a number of sweetheart real estate deals, none other than Donald Trump leased the space and opened a new tennis and fitness club. Trump renovated the aged space, turning its third floor annex into an uber-exclusive court for the rich and famous, hosting movie stars and celebrities willing to pay in cash (no credit cards accepted). The now spotless clay courts operated in semi-secrecy for 30 years until Trump’s lease, having been month-to-month for the final decade of its existence was finally given over in 2009 to create, surprisingly not an even more exclusive space, but a full-service lounge and rest area for MTA workers. However, the dream of train station tennis was not yet dead. While Grand Central went without a tennis court for a couple of years, the Vanderbilt Tennis Club moved into the fourth floor of the station in 2011. This new location features a regulation-size tennis court, practice courts and other limited fitness services. While not as exclusive as Trump’s courts, the costs (around $100-$250 an hour) do seem geared towards a certain economic echelon.The main court is actually located behind the the top portion of the famous facade window, so next time you look at that famous architectural spot remember that you could get a few rounds in if you’ve got the money.  Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzUwYzNmYWU2NTlhMDQ2MmRjZl8zNDAyMjhfMjQ2NTU4OTg4NzE2MzY4XzY2MTUyMTJfby5qcGciXSxbInAiLCJjb252ZXJ0IiwiLXF1YWxpdHkgODEgLWF1dG8tb3JpZW50Il0sWyJwIiwidGh1bWIiLCIzNzJ4MjQ4IyJdXQ',
                website: 'http://www.vanderbilttennisclub.com/',
                categories: {'sports': 1, 'health and fitness': 1, 'real estate': 1}
            },
            {
                name: '190 Bowery',
                indoor_outdoor: 1,
                location: '190 BoweryNew York, New York, 10012United States',
                description: '190 Bowery looks abandoned, forgotten, covered in trash and graffiti on an otherwise well-maintained major street in Manhattan. A hulking six story, 72-room mass built as the Germania Bank Building in 1898, today the structure is a single family home.It’s the American Dream as a house, a building that went from rags to riches on a street once known for its murders, now known for its centrality. Photographer Jay Maisel broke the bank when he bought the bank in 1966 for $102,000. Back then, the Bowery wasn’t a place you went so much as ended up, and the main floor (now a basketball court) was allegedly knee-deep in garbage and coated in soot, with “every single thing that can come out of a human body” left on the doorstep. Maisel’s parents cried. Today, the bohemian castle may look deceptively decrepit on the outside, but inside it’s a dream. A home-made ventilation system (to deter the insane expense of what central air would cost in such a space) consists of a network of plastic tubing throughout the building. The original 1898 copper cage elevator still works, the second and third floor are gallery spaces, the  fifth floor has various workshops (including a room dedicated to Mylar-window shades), the sixth floor has bedrooms, bathrooms, and the kitchen, and the roof a wowing view of lower Manhattan.The family occasionally finds new rooms, and take-out is a “riot”, since no right-minded delivery boy believes such a hulk houses just four people.Today, 190 Bowery is estimated of having a worth anywhere between $30 and $70 million, and is certainly in the running for best property snag of all time.Care to take a look inside? Maisel teaches private photography classes in his home, but it’ll cost you $5,000.Update September 2016: This place has been sold to be turned into high-end office space. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL3liNjMydG0zYWlzYTE2NDI4OTE5ZTUzMDM1YmYxX0Z1bGxTaXplUmVuZGVyLmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA4MSAtYXV0by1vcmllbnQiXSxbInAiLCJ0aHVtYiIsIjM3MngyNDgjIl1d/FullSizeRender.jpg',
                website: 'https://www.atlasobscura.com/places/190-Bowery',
                categories: {'science': 1, 'travel': 1, 'finance': 1}
            },
            {
                name: 'Hare Krishna Tree',
                indoor_outdoor: 1,
                location: 'Tompkins Square Park (btw Ave. A & Ave. Band btw East 7th St. & East 10th St.)New York, New York, 10009United States',
                description: 'For a hundred years this elegant American elm at the center of Tompkins Square Park was just a tree. Then, in 1966, the Hare Krishna mantra was chanted under its sprawling canopy for the first time, and it became the birthplace of a religion.To Hare Krishnas, this tree is a sacred site. For everyone else, it would be easy to stroll by the old elm in Manhattan’s East Village and have no idea it’s a religious landmark. It’s a handsome tree — American elms are quite rare now, known for their wide-stretching canopies — but otherwise inconspicuous. But if you happened to wander by on October 9, 1966, you would have heard the “Hare Krishna” mantra chanted publicly for the first time outside of India, marking the birth of the spiritual movement in the West.At the base of the tree, Bhaktivedanta Swami Prabhupada and a group of robed followers spent two hours chanting, dancing, playing tambourines and cymbals, and seeking Krishna — a pure and blissful consciousness. Among them was Beatnik poet Allen Ginsberg, who was living nearby. He later wrote, “The ecstasy of chant or mantra has replaced LSD and other drugs for many of the swami’s followers.”At the time, lower Manhattan was the epicenter of a bohemian counterculture, the Haight-Ashbury of the East Coast. Hippies flowed into Tompkins Square Park, which has long been both a neighborhood respite and a symbol of subversion, where activists staged anti-war protests and women marched for liberation. Not long after the Swami first sang Hare Krishna under the old elm tree, legends like Jimi Hendrix and the Grateful Dead played at the park’s new bandshell.If you venture a few blocks from the park you’ll find 26 Second Avenue, where Swami Prabhupada founded the International Society for Krishna Consciousness. He rented a storefront that would serve as both the religious movement’s headquarters and a Hare Krishna temple. Amazingly, the temple remains there today, next to a vintage boutique.Devotees still travel to Tompkins Square Park to visit the Hare Krishna Tree, where George Harrison once sought a higher consciousness, leaving garland and flowers around the holy elm’s wide trunk.Open to the public, about a 10-minute walk from various subway lines. The tree is the large elm at the south end of the Central Grove section, in just about the middle of the park. Sign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzc4YjZjM2VkYzgwZGU1MzY0ZF9UcmVlIDYuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiMzcyeDI0OCMiXV0/Tree%206.jpg',
                website: 'http://www.nycgovparks.org/parks/tompkins-square-park/highlights/10823',
                categories: {'religion and spirituality': 1, 'art and entertainment': 1, 'religion and spirituality': 1}
            },
            {
                name: '284 Broome Street',
                indoor_outdoor: 1,
                location: '284 Broome StreetNew York, New York, 10002United States',
                description: 'The block of Broome Street between Allen and Eldridge is the smelliest block in New York City. The New York Times Magazine tested the area with a number of olfactory experts, who all agreed it is the worst smell known to the City.If you happen to think you can handle anything, or that you’ve smelled worse, hop a subway down to the Lower East Side and take a few whiffs. Better yet, challenge a friend and make the loser buy lunch at Shopsin’s, only a few blocks away.A local magazine conducted an investigation on the smell recently, and figured out that the smell was coming from  stacked boxes of raw poultry that have been marinating in the sun. While you would think that the place would be slapped with a fine or a warning from the health inspectors, but the smell is technically legal, so the legendary scent of Broome street lives on, unopposed.Accessible from B,D Trains at Grand Street StationSign up for our newsletter and get the best of Atlas Obscura in your inbox.',
                img: 'https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzZiMWJlOGI5ZDRhMzM1YTQ5ZGRhZGQzNTdiNTFmNjJic21lbGxpZXN0LWJsb2NrMS5qcGciXSxbInAiLCJjb252ZXJ0IiwiLXF1YWxpdHkgODEgLWF1dG8tb3JpZW50Il0sWyJwIiwidGh1bWIiLCIzNzJ4MjQ4IyJdXQ/smelliest-block1.jpg',
                website: 'https://www.atlasobscura.com/places/284-Broome-Street',
                categories: {'style and fashion': 1, 'technology and computing': 1, 'society': 1}
            }
        ]
    }
}